version: 0.2    
phases:
  install:
    runtime-versions: 
      nodejs: 10
    commands:
      - echo installing maven
  build: 
    commands:
      - pwd
      - pushd src/main/resources/frontend/blackstone-app && npm install && popd
      - mvn install
      - mvn clean package
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
    
cache:
  paths:
    - '/root/.m2/**/*'