version: 0.2

env:
  variables: 
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    
phases:
  install:
    runtime-versions: 
      nodejs: 10
    commands:
      - echo installing maven
  build: 
    commands:
      - mvn install
      - mvn clean package
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
    
cache:
  paths:
    - '/root/.m2/**/*'